### ISSUE TITLE
can I point xLights at this?

### ISSUE THREAD

**Issue by jschwalbe** [jeffc/mqtt2e131#1]
Hi!
Trying to understand the scope of this project. I have a bunch of Hue/WiFi bulbs set up in HA already, but none of them can be controlled via e1.31 protocol. I'm looking to bridge the two protocols.. in other words I'd like to add a HA controlled bulb to xLights (which requires the e131 protocol).

so.. xLights --(e131)--> [ `mqtt2e131`?? ] --> HA --> bulb

Is this possible with `mqtt2e131`? Thanks :)

**Comment by jeffc** [comment]
Hey jschwable,

I actually started this project for the opposite case: I have a bunch of lights on e131 controllers (which, coincidentally, I drive using xLights) that I wanted to be able to control from HA. mqtt2e131 exposes the e131 lights as MQTT in HA's autodiscovery format, so they show up as lights in HA. Unfortunately, that's not what you're looking for.

It wouldn't be super hard if you wanted to use the same libraries to write something that goes the other way, but you might not have great results: in my experience, HA lights don't respond instantaneously to updates (there's latency of tens to hundreds of milliseconds), so trying to run sequences where you need multiple consecutive updates with 50ms timing (ie, a 20 fps animation) would probably just stutter and bog down Home Assistant. There are Hue light libraries that you could look at to control the bulbs directly (ie, not through HA), but I don't know what the latency is like on those since I don't have any Hue lights.

Good luck!

**Comment by jschwalbe** [comment]
Thanks much! I'll check into that. Might be too rusty :) Fortunately I don't need quick updates, just enough to make the spotlights change colors occasionally.
